# Generated by Django 5.2.7 on 2025-11-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home_services', 'Home Services'), ('repair_maintenance', 'Repair & Maintenance'), ('lifestyle_help', 'Lifestyle & Personal Help'), ('outdoor_gardening', 'Outdoor & Gardening'), ('moving_logistics', 'Moving & Logistics')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_identity_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('house_num', models.CharField(max_length=20)),
                ('full_address', models.CharField(max_length=255)),
                ('special_add_ons', models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], max_length=10, null=True)),
                ('optional_note', models.TextField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('sw-ar-en', 'Swedish - Arabic - English'), ('ar', 'Arabic'), ('en', 'English'), ('sv', 'Swedish')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('password', models.CharField(max_length=255)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('desired_services', models.ManyToManyField(to='accounts.service')),
            ],
        ),
    ]
