# Generated by Django 5.2.7 on 2025-11-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='special_add_ons',
        ),
        migrations.AddField(
            model_name='customer',
            name='custom_addons',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
