# Generated by Django 5.2.7 on 2025-12-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='entry_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='parking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='pronouns',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
