# Generated by Django 5.2.7 on 2026-01-24 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='servicecomment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service_title',
            field=models.CharField(help_text='Service name (e.g. Deep Cleaning)', max_length=255),
        ),
    ]
