# Generated by Django 5.2.7 on 2025-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_special_add_ons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custom_addons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
