# Generated by Django 5.2.7 on 2025-12-24 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='country',
            field=models.CharField(choices=[('Syria', 'Syria'), ('office', 'Office'), ('vacation', 'Vacation Home'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('incident_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('incident_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('involved_person', models.CharField(blank=True, max_length=100)),
                ('preferred_resolution', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='incidents/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
