# Generated by Django 5.2.7 on 2025-12-26 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customerlocation_country_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_handling', models.CharField(choices=[('mat', 'Leave under mat'), ('garden', 'Hide in the garden'), ('hand', 'Hand directly'), ('custom', 'Custom')], default='mat', max_length=20)),
                ('key_custom_instructions', models.CharField(blank=True, max_length=255)),
                ('alarm_code', models.CharField(blank=True, max_length=50)),
                ('products_supplies', models.CharField(choices=[('company', 'Company products'), ('customer', 'Customer products')], default='customer', max_length=20)),
                ('cleaning_material_location', models.CharField(blank=True, max_length=255)),
                ('special_requests', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
