# Generated by Django 5.2.7 on 2026-01-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chatmessage_file_alter_chatmessage_text'),
        ('home', '0015_rename_refunded_amount_businessbooking_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('private', 'Private'), ('business', 'Business')], max_length=10)),
                ('booking_id', models.PositiveIntegerField()),
                ('kitchen_counters', models.BooleanField(default=False)),
                ('kitchen_sink', models.BooleanField(default=False)),
                ('kitchen_floor', models.BooleanField(default=False)),
                ('kitchen_fridge', models.BooleanField(default=False)),
                ('bathroom_scrub', models.BooleanField(default=False)),
                ('bathroom_mirrors', models.BooleanField(default=False)),
                ('bathroom_floor', models.BooleanField(default=False)),
                ('bedroom_beds', models.BooleanField(default=False)),
                ('bedroom_dust', models.BooleanField(default=False)),
                ('bedroom_floor', models.BooleanField(default=False)),
                ('living_dust', models.BooleanField(default=False)),
                ('living_vacuum', models.BooleanField(default=False)),
                ('living_glass', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_business', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='home.businessbooking')),
                ('booking_private', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='home.privatebooking')),
            ],
            options={
                'unique_together': {('booking_type', 'booking_id')},
            },
        ),
    ]
