# Generated by Django 5.2.7 on 2026-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_referral_code_alter_referral_referred_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_referral_discount',
            field=models.BooleanField(default=False),
        ),
    ]
