# Generated by Django 5.2.7 on 2026-01-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bookingchecklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingchecklist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookingchecklist',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='bookingchecklist',
            name='booking_type',
        ),
    ]
