# Generated by Django 5.2.7 on 2026-01-30 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bookingrequestfix_customernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('hero_headline', models.CharField(max_length=150)),
                ('hero_subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/hero/')),
                ('hero_cta_text', models.CharField(blank=True, max_length=60)),
                ('hero_cta_url', models.URLField(blank=True)),
                ('intro_text', models.TextField(blank=True)),
                ('pricing_intro', models.TextField(blank=True)),
                ('highlight_title', models.CharField(blank=True, max_length=120)),
                ('highlight_subtitle', models.CharField(blank=True, max_length=255)),
                ('contact_title', models.CharField(blank=True, max_length=120)),
                ('contact_subtitle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='accounts.service')),
            ],
            options={
                'ordering': ['service__label'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=180)),
                ('price_label', models.CharField(blank=True, max_length=80)),
                ('price_value', models.CharField(blank=True, help_text='e.g. $250', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='accounts.servicedetail')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HighlightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=70)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_cards', to='accounts.servicedetail')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExclusionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_cards', to='accounts.servicedetail')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(help_text='Write each bullet on a new line.')),
                ('icon', models.CharField(blank=True, help_text='Optional icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_cards', to='accounts.servicedetail')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
