# Generated by Django 5.2.7 on 2026-01-06 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_paymentmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_reminders', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=True)),
                ('phone', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=True)),
                ('in_app', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=20)),
                ('secondary_language', models.CharField(blank=True, max_length=20, null=True)),
                ('timing', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('any', 'Any Time')], default='any', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
