# Generated by Django 5.2.7 on 2026-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_has_referral_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_points', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited (Gold)', null=True)),
                ('description', models.CharField(help_text='Short description shown to users', max_length=255)),
                ('benefits', models.TextField(help_text='What does the user get in this tier?')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'min_points'],
            },
        ),
    ]
