# Generated by Django 5.2.7 on 2026-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loyaltytier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltytier',
            options={},
        ),
        migrations.AddField(
            model_name='loyaltytier',
            name='color',
            field=models.CharField(default='bronze', help_text='bronze / silver / gold', max_length=20),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loyaltytier',
            name='max_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
