# Generated by Django 5.2.7 on 2026-01-31 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_servicedetail_pricingtier_highlightcard_and_more'),
        ('home', '0008_bookingmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'ordering': ['private_service__title']},
        ),
        migrations.RemoveField(
            model_name='servicedetail',
            name='service',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='private_service',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='home.privateservice'),
            preserve_default=False,
        ),
    ]
