# Generated by Django 5.2.7 on 2026-02-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_servicedetail_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChecklistCard",
        ),
        migrations.DeleteModel(
            name="HighlightCard",
        ),
        migrations.DeleteModel(
            name="PricingTier",
        ),
        migrations.DeleteModel(
            name="ExclusionCard",
        ),
        migrations.DeleteModel(
            name="ServiceDetail",
        ),
    ]
