# Generated by Django 5.2.7 on 2026-01-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bookingchecklist_is_initialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingchecklist',
            name='is_initialized',
        ),
    ]
