# Generated by Django 5.2.7 on 2026-01-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_service_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customernotification',
            name='notification_type',
            field=models.CharField(choices=[('request_fix', 'Request Fix'), ('approve_work', 'Approve Work'), ('incident', 'Incident'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
