# Generated by Django 5.2.7 on 2026-01-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_types', models.JSONField(blank=True, default=list)),
                ('preferred_products', models.JSONField(blank=True, default=list)),
                ('excluded_products', models.JSONField(blank=True, default=list)),
                ('frequency', models.CharField(blank=True, max_length=30, null=True)),
                ('priorities', models.JSONField(blank=True, default=list)),
                ('lifestyle_addons', models.JSONField(blank=True, default=list)),
                ('assembly_services', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.customer')),
            ],
        ),
    ]
