# Generated by Django 5.2.7 on 2026-01-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpreferences',
            name='frequency_custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='priorities_custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='products_custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
