# Generated by Django 5.2.7 on 2026-01-21 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_discountcode_max_uses_discountcode_used_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('private', 'Private'), ('business', 'Business')], max_length=10)),
                ('booking_id', models.PositiveIntegerField()),
                ('service_title', models.CharField(max_length=255)),
                ('service_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('punctuality', models.PositiveSmallIntegerField()),
                ('quality', models.PositiveSmallIntegerField()),
                ('professionalism', models.PositiveSmallIntegerField()),
                ('value', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_service_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'booking_type', 'booking_id'), name='unique_review_per_booking_per_customer')],
            },
        ),
    ]
