# Generated by Django 5.2.7 on 2026-02-02 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_provider_admin_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('main', 'Main'), ('electrical', 'Electrical')], default='main', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('global_super', 'Global Super'), ('electrical_super', 'Electrical Super'), ('electrical_admin', 'Electrical Admin')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
