# Generated by Django 5.2.7 on 2026-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_useraccessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='desired_services',
            field=models.ManyToManyField(blank=True, to='accounts.service'),
        ),
        migrations.AlterField(
            model_name='useraccessprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('global_super', 'Global Super')], max_length=30),
        ),
        migrations.AlterField(
            model_name='useraccessprofile',
            name='site',
            field=models.CharField(choices=[('main', 'Main')], default='main', max_length=20),
        ),
    ]
