# Generated by Django 5.2.7 on 2026-03-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_paymentmethod_stripe_fields'),
        ('accounts', '0017_passwordresetotp'),
    ]

    operations = [
    ]
