# Generated by Django 5.2.7 on 2026-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_bookingchecklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='country',
            field=models.CharField(choices=[('Sweden', 'Sweden'), ('Syria', 'Syria'), ('other', 'Other')], max_length=20),
        ),
    ]
