# Generated by Django 5.2.7 on 2026-08-02 15:47

from django.db import migrations, models


def initialize_document_numbers(apps, schema_editor):
    Customer = apps.get_model('accounts', 'Customer')
    Invoice = apps.get_model('accounts', 'Invoice')
    DocumentSequence = apps.get_model('accounts', 'DocumentSequence')

    last_customer_number = 2499
    for customer in Customer.objects.order_by('pk').iterator():
        last_customer_number += 1
        Customer.objects.filter(pk=customer.pk).update(customer_number=last_customer_number)

    DocumentSequence.objects.update_or_create(
        key='customer',
        defaults={'last_value': last_customer_number},
    )
    customer_numbers = dict(Customer.objects.values_list('pk', 'customer_number'))
    for invoice in Invoice.objects.all().iterator():
        Invoice.objects.filter(pk=invoice.pk).update(
            customer_number=str(customer_numbers.get(invoice.customer_id) or ''),
        )

    last_invoice_number = 100
    for invoice in Invoice.objects.filter(status='DRAFT').order_by('pk').iterator():
        last_invoice_number += 1
        old_number = invoice.invoice_number
        new_number = f'INV-{last_invoice_number}'
        updates = {'invoice_number': new_number}
        if not invoice.payment_reference or invoice.payment_reference == old_number:
            updates['payment_reference'] = new_number
        Invoice.objects.filter(pk=invoice.pk).update(**updates)

    DocumentSequence.objects.update_or_create(
        key='invoice',
        defaults={'last_value': last_invoice_number},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_invoice_draft_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(initialize_document_numbers, migrations.RunPython.noop),
    ]
