# Generated by Django 5.2.7 on 2026-08-02 18:31

from decimal import Decimal
from django.db import migrations, models


def derive_existing_discount_percentages(apps, schema_editor):
    InvoiceLineItem = apps.get_model('accounts', 'InvoiceLineItem')
    for item in InvoiceLineItem.objects.exclude(discount_amount=0).iterator():
        base = (item.quantity or Decimal('0.00')) * (item.unit_price or Decimal('0.00'))
        if base > 0:
            percent = ((item.discount_amount / base) * Decimal('100')).quantize(Decimal('0.01'))
            InvoiceLineItem.objects.filter(pk=item.pk).update(discount_percent=min(percent, Decimal('100.00')))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_documentsequence_customer_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.RunPython(derive_existing_discount_percentages, migrations.RunPython.noop),
    ]
