"""
Django settings for PRO project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except Exception:
    load_dotenv = None

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env via python-dotenv if available
if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")

# Fallback simple .env loader
env_path = BASE_DIR / ".env"
if env_path.exists():
    with env_path.open("r", encoding="utf-8") as env_file:
        for line in env_file:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'hembla-experten.se',
    'www.hembla-experten.se',
    '45.93.137.166',
]

CSRF_TRUSTED_ORIGINS = [
    "https://hembla-experten.se",
    "https://www.hembla-experten.se",
]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
SITE_ID = 1
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountLoggingAdapter"
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'home.apps.HomeConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
]

JAZZMIN_SETTINGS = {
    "site_title": "Admin Dashboard",
    "site_header": "Cleaning Platform",
    "site_brand": "Control Panel",
    "welcome_sign": "Welcome Boss 👋",
    "site_logo": "images/logo.png",  # اختياري
    "login_logo": None,

    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    "icons": {
        "yourapp.PrivateBooking": "fas fa-calendar-check",
        "yourapp.PrivateService": "fas fa-broom",
        "yourapp.PrivateAddon": "fas fa-puzzle-piece",
        "yourapp.BusinessBooking": "fas fa-briefcase",
        "yourapp.CallRequest": "fas fa-phone",
        "yourapp.EmailRequest": "fas fa-envelope",
        "auth.User": "fas fa-user",
    },

    "theme": "darkly",  # super فخم
}

JAZZMIN_SETTINGS["icons"].update({
    "yourapp.Contact": "fas fa-inbox",
    "yourapp.CallRequest": "fas fa-phone-volume",
    "yourapp.EmailRequest": "fas fa-envelope-open-text",
})
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'PRO.middleware.AdminSiteAccessGuard',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailPhoneUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ROOT_URLCONF = 'PRO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 'accounts.context_processors.chat_notifications',
            ],
        },
    },
]
TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "accounts.context_processors.unread_messages",
    "accounts.context_processors.sidebar_customer",
]
WSGI_APPLICATION = 'PRO.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'cleaning'),
        'USER': os.getenv('POSTGRES_USER', 'cleaning'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    },
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'hembla_db',
#         'USER': 'hembla_user',
#         'PASSWORD': 'Hembla123456789@',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ("en", "English"),
    ("ar", "العربية"),
    ("sv", "Svenska"),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, "media")
CORS_ALLOW_ALL_ORIGINS = True

# Email (Hostinger SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.hostinger.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "services@hembla-experten.se"
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = "Hembla Experten <services@hembla-experten.se>"
EMAIL_TIMEOUT = 10

#book's email
ADMIN_ALERT_EMAIL = "services@hembla-experten.se"

# Stripe
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_CURRENCY = os.getenv("STRIPE_CURRENCY", "sek").lower()


def _stripe_key_mode(value, publishable=False):
    if not value:
        return ""
    if publishable:
        if value.startswith("pk_live_"):
            return "live"
        if value.startswith("pk_test_"):
            return "test"
    else:
        if value.startswith("sk_live_"):
            return "live"
        if value.startswith("sk_test_"):
            return "test"
    raise ImproperlyConfigured("Stripe keys must use the expected pk_/sk_ prefixes.")


_stripe_publishable_mode = _stripe_key_mode(STRIPE_PUBLISHABLE_KEY, publishable=True)
_stripe_secret_mode = _stripe_key_mode(STRIPE_SECRET_KEY)
if _stripe_publishable_mode != _stripe_secret_mode:
    raise ImproperlyConfigured(
        "Stripe publishable and secret keys must both be test keys or both be live keys."
    )
if _stripe_secret_mode and not STRIPE_WEBHOOK_SECRET:
    raise ImproperlyConfigured(
        "STRIPE_WEBHOOK_SECRET is required whenever Stripe keys are configured."
    )
if STRIPE_WEBHOOK_SECRET and not STRIPE_WEBHOOK_SECRET.startswith("whsec_"):
    raise ImproperlyConfigured("STRIPE_WEBHOOK_SECRET must use the Stripe whsec_ format.")

# --- SMTP sanity + startup log (no secrets) ---
import logging
logger = logging.getLogger("PRO.settings")
logger.info("EMAIL_BACKEND=%s", EMAIL_BACKEND)
logger.info("EMAIL_HOST=%s", EMAIL_HOST)
logger.info("EMAIL_PORT=%s", EMAIL_PORT)
logger.info("EMAIL_USE_SSL=%s", EMAIL_USE_SSL)


##################################################################SERVER

