# Generated by Django 5.2.7 on 2026-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('RESUMED', 'Service Resumed'), ('COMPLETED', 'Service Completed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('RESUMED', 'Service Resumed'), ('COMPLETED', 'Service Completed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
    ]
