# Generated by Django 5.2.7 on 2026-01-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
