# Generated by Django 5.2.7 on 2025-11-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Support'), ('pricing', 'Pricing'), ('booking', 'Booking')], max_length=50)),
                ('preferred_method', models.CharField(default='email', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='contact_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
