# Generated by Django 5.2.7 on 2026-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
