# Generated by Django 5.2.7 on 2025-12-29 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_availablezipcode_businessaddon_businessbundle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='provider_on_way_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Service Started'), ('PAUSED', 'Service Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='provider_on_way_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Service Started'), ('PAUSED', 'Service Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datesurcharge',
            name='rule_type',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('date', 'Date')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datesurcharge',
            name='surcharge_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='datesurcharge',
            name='weekday',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='notavailableziprequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.privateservice'),
        ),
        migrations.AlterField(
            model_name='privatebooking',
            name='schedule_mode',
            field=models.CharField(choices=[('same', 'Same'), ('per_service', 'Per Service')], default='same', max_length=20),
        ),
    ]
