# Generated by Django 5.2.7 on 2026-01-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_businessbooking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='quoted_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Expected service duration in minutes'),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='quoted_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Expected service duration in minutes'),
        ),
    ]
