# Generated by Django 5.2.7 on 2026-01-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedbackrequest_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
