# Generated by Django 5.2.7 on 2025-11-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(default='Full Time', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
