# Generated by Django 5.2.7 on 2026-01-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_businessbooking_quoted_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='points_awarded',
            field=models.IntegerField(blank=True, help_text='Points decided by admin after completion', null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='points_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='points_processed',
            field=models.BooleanField(default=False, help_text='Prevent double points processing'),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='points_awarded',
            field=models.IntegerField(blank=True, help_text='Points decided by admin after completion', null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='points_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='points_processed',
            field=models.BooleanField(default=False, help_text='Prevent double points processing'),
        ),
    ]
