# Generated by Django 5.2.7 on 2026-01-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_discountcode'),
        ('home', '0004_businessbooking_points_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.discountcode'),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.discountcode'),
        ),
    ]
