# Generated by Django 5.2.7 on 2026-01-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_businessbooking_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=20)),
                ('booking_id', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
