# Generated by Django 5.2.7 on 2025-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
