# Generated by Django 5.2.7 on 2026-01-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_bookingtimeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbooking',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='scheduled_at',
        ),
    ]
