# Generated by Django 5.2.7 on 2025-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_application_area_application_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('business', 'Business'), ('private', 'Private')], default='business', max_length=20)),
                ('selected_bundle', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_services', models.JSONField(blank=True, null=True)),
                ('addons', models.JSONField(blank=True, null=True)),
                ('office_size', models.CharField(blank=True, max_length=50, null=True)),
                ('employees', models.CharField(blank=True, max_length=50, null=True)),
                ('floors', models.CharField(blank=True, max_length=50, null=True)),
                ('restrooms', models.CharField(blank=True, max_length=5, null=True)),
                ('kitchen', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('several_per_week', 'Several times per week'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_demand', 'On-demand'), ('yearly', 'Yearly')], max_length=50, null=True)),
                ('times_per_week', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, choices=[('before_hours', 'Before office hours'), ('during_hours', 'During office hours'), ('after_hours', 'After office hours')], max_length=50, null=True)),
                ('days_of_week', models.JSONField(blank=True, null=True)),
                ('custom_date', models.DateField(blank=True, null=True)),
                ('custom_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
