# Generated by Django 5.2.7 on 2025-11-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_businessbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessbooking',
            old_name='kitchen',
            new_name='kitchen_cleaning',
        ),
        migrations.RenameField(
            model_name='businessbooking',
            old_name='days_of_week',
            new_name='services_needed',
        ),
        migrations.RemoveField(
            model_name='businessbooking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='businessbooking',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='businessbooking',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='businessbooking',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='businessbooking',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='num_employees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='selected_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='custom_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='floors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='office_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='restrooms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
