# Generated by Django 5.2.7 on 2026-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_businessbooking_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
