# Generated by Django 5.2.7 on 2025-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_kitchen_businessbooking_kitchen_cleaning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommended', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='business_services/')),
            ],
        ),
    ]
