# Generated by Django 5.2.7 on 2026-01-31 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bookingmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateservice',
            name='hero_cta_text',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='privateservice',
            name='hero_cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='privateservice',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='private/hero/'),
        ),
        migrations.AddField(
            model_name='privateservice',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='privateservice',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='privateservice',
            name='starting_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('checklist', 'Checklist'), ('exclusion', 'Exclusion'), ('highlight', 'Highlight'), ('info', 'Info')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.privateservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.servicesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
