# Generated by Django 5.2.7 on 2025-11-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_businessservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbooking',
            name='restrooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
