# Generated by Django 5.2.7 on 2026-01-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_privateservice_hero_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEcoPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Eco-Friendly Promise', max_length=140)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Add To Cart', max_length=50)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eco_promise', to='home.privateservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEcoPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='home.serviceecopromise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get a Quick Estimate', max_length=120)),
                ('property_label', models.CharField(default='Property Size (m²)', max_length=120)),
                ('bedrooms_label', models.CharField(default='Number of Bedrooms', max_length=120)),
                ('cta_text', models.CharField(default='Calculate Estimate', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to='home.privateservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Transparent Pricing', max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('price_label', models.CharField(blank=True, max_length=80)),
                ('price_value', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.URLField(blank=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='home.privateservice')),
            ],
        ),
    ]
