# Generated by Django 5.2.7 on 2025-11-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_businessbooking_restrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('discount', models.CharField(blank=True, max_length=20, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bundles/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='selected_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='home.businessbundle'),
        ),
    ]
