# Generated by Django 5.2.7 on 2026-01-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_serviceecopromise_serviceecopoint_serviceestimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepricing',
            name='card_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicepricing',
            name='price_note',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
