# Generated by Django 5.2.7 on 2026-01-04 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_businessbooking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessbooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('COMPLETED', 'Service Completed'), ('ASSIGNED', 'Provider Assigned'), ('RESUMED', 'Service Resumed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('COMPLETED', 'Service Completed'), ('ASSIGNED', 'Provider Assigned'), ('RESUMED', 'Service Resumed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.CreateModel(
            name='NoShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('private', 'Private'), ('business', 'Business')], max_length=10)),
                ('booking_id', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('provider_note', models.TextField(blank=True, null=True)),
                ('reviewed_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_show_reports_sent', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_show_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
