# Generated by Django 5.2.7 on 2026-01-06 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_businessbooking_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbooking',
            name='incident_status',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='incident_status',
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('RESUMED', 'Service Resumed'), ('COMPLETED', 'Service Completed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('RESUMED', 'Service Resumed'), ('COMPLETED', 'Service Completed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.CreateModel(
            name='BookingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('private', 'Private'), ('business', 'Business')], max_length=10)),
                ('booking_id', models.PositiveIntegerField()),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kept_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_type', models.CharField(choices=[('FULL', 'Full Refund'), ('PARTIAL', 'Partial Refund'), ('NONE', 'No Refund')], max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
