# Generated by Django 5.2.7 on 2026-01-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_servicepricing_card_title_servicepricing_price_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesection',
            name='service',
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, help_text='Example: bi-check-circle, bi-exclamation-circle', max_length=50)),
                ('body', models.TextField(help_text='One bullet per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.privateservice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SectionItem',
        ),
        migrations.DeleteModel(
            name='ServiceSection',
        ),
    ]
