# Generated by Django 5.2.7 on 2025-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_businessbundle_alter_businessbooking_selected_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbundle',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='businessbundle',
            name='features',
        ),
        migrations.RemoveField(
            model_name='businessbundle',
            name='is_active',
        ),
        migrations.AddField(
            model_name='businessbundle',
            name='addons',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbundle',
            name='what_included',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessbundle',
            name='why_choose',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessbundle',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
