# Generated by Django 5.2.7 on 2026-01-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_businessbooking_incident_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='incident_status',
            field=models.CharField(blank=True, choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=30),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='incident_status',
            field=models.CharField(blank=True, choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('COMPLETED', 'Service Completed'), ('ASSIGNED', 'Provider Assigned'), ('RESUMED', 'Service Resumed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('COMPLETED', 'Service Completed'), ('ASSIGNED', 'Provider Assigned'), ('RESUMED', 'Service Resumed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.DeleteModel(
            name='BookingRefund',
        ),
    ]
