# Generated by Django 5.2.7 on 2025-11-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_businessbundle_add_ons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbundle',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
