# Generated by Django 5.2.7 on 2026-02-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_servicesection_service_servicecard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateservice',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
