# Generated by Django 5.2.7 on 2026-02-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_privateservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateaddon',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
