# Generated by Django 5.2.7 on 2025-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_businessbundle_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessservice',
            name='icon',
            field=models.ImageField(default='', upload_to='services/'),
            preserve_default=False,
        ),
    ]
