# Generated by Django 5.2.7 on 2026-01-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_businessbooking_refund_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessbooking',
            old_name='refunded_amount',
            new_name='refund_amount',
        ),
        migrations.RenameField(
            model_name='privatebooking',
            old_name='refunded_amount',
            new_name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='businessbooking',
            name='incident_status',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='incident_status',
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('RESUMED', 'Service Resumed'), ('COMPLETED', 'Service Completed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
        migrations.AlterField(
            model_name='privatebooking',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Order Placed'), ('SCHEDULED', 'Confirmed / Scheduled'), ('ASSIGNED', 'Provider Assigned'), ('ON_THE_WAY', 'Provider On The Way'), ('STARTED', 'Check in / Service Started'), ('PAUSED', 'Service Paused'), ('RESUMED', 'Service Resumed'), ('COMPLETED', 'Service Completed'), ('CANCELLED_BY_CUSTOMER', 'Cancelled by Customer'), ('NO_SHOW', 'No Show'), ('INCIDENT_REPORTED', 'Incident Reported'), ('REFUNDED', 'Refunded')], default='ORDERED', max_length=30),
        ),
    ]
