# Generated by Django 5.2.7 on 2025-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_businessservice_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessservice',
            name='description_service_aviable',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
