# Generated by Django 5.2.7 on 2025-11-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_businessservice_description_service_aviable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('emoji', models.CharField(default='➕', max_length=5)),
            ],
        ),
    ]
