# Generated by Django 5.2.7 on 2025-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_businessaddon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbooking',
            name='times_per_week',
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='frequency',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
