# Generated by Django 5.2.7 on 2025-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_businessbooking_times_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='days_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessbooking',
            name='restrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10, null=True),
        ),
    ]
