# Generated by Django 5.2.7 on 2025-11-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_businessbooking_days_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbooking',
            name='path_type',
            field=models.CharField(default='bundle', max_length=20),
        ),
    ]
