# Generated by Django 5.2.7 on 2025-11-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_businessbooking_path_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_is_available', models.BooleanField(default=False)),
                ('booking_method', models.CharField(blank=True, choices=[('online', 'Book Online Now'), ('call', 'Request a Call'), ('email', 'Send Email')], max_length=20, null=True)),
                ('call_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('call_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('call_email', models.CharField(blank=True, max_length=255, null=True)),
                ('call_time', models.CharField(blank=True, max_length=255, null=True)),
                ('call_message', models.TextField(blank=True, null=True)),
                ('call_language', models.CharField(blank=True, max_length=100, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_message', models.TextField(blank=True, null=True)),
                ('email_attachment', models.FileField(blank=True, null=True, upload_to='private/email_attachments/')),
                ('main_category', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_services', models.JSONField(blank=True, null=True)),
                ('service_answers', models.JSONField(blank=True, null=True)),
                ('addons_selected', models.JSONField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time_window', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_type', models.CharField(blank=True, choices=[('onetime', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal')], max_length=50, null=True)),
                ('special_timing_requests', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rot_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit Card'), ('paypal', 'Paypal'), ('klarna', 'Klarna'), ('swish', 'Swish')], max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=10, null=True)),
                ('card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='private/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommended', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='private/services/')),
                ('slug', models.SlugField(unique=True)),
                ('questions', models.JSONField(blank=True, null=True)),
                ('addons', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.privatemaincategory')),
            ],
        ),
    ]
