# Generated by Django 5.2.7 on 2026-03-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_privatebookingdraft'),
        ('home', '0020_businessservice_detail_description'),
    ]

    operations = [
    ]
