# Generated by Django 5.2.7 on 2026-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20260311_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatebooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit Card')], max_length=50, null=True),
        ),
    ]
