# Generated by Django 5.2.7 on 2025-11-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_emailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemaincategory',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
