# Generated by Django 5.2.7 on 2025-11-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_privatemaincategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateservice',
            name='addons',
        ),
        migrations.CreateModel(
            name='PrivateAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='private/addons/')),
                ('slug', models.SlugField(unique=True)),
                ('form_html', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons_list', to='home.privateservice')),
            ],
        ),
    ]
