# Generated by Django 5.2.7 on 2025-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_privateservice_addons_privateaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebooking',
            name='End_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='day_work_best',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
