# Generated by Django 5.2.7 on 2025-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_privatebooking_end_date_privatebooking_day_work_best'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatebooking',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
