# Generated by Django 5.2.7 on 2025-12-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_privatebooking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatebooking',
            name='call_email',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='call_fullname',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='call_language',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='call_message',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='call_phone',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='call_time',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='email_attachment',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='email_message',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='email_subject',
        ),
    ]
