# Generated by Django 5.2.7 on 2025-12-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_privatebooking_call_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatebooking',
            old_name='day_work_best',
            new_name='service_schedules',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='appointment_time_window',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='frequency_type',
        ),
        migrations.RemoveField(
            model_name='privatebooking',
            name='special_timing_requests',
        ),
    ]
