# Generated by Django 5.2.7 on 2026-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_privateservice_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateGenericAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='private/generic_addons/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Extra time added by this generic add-on in minutes.')),
                ('price_currency', models.CharField(choices=[('SEK', 'Swedish Krona (SEK)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='USD', max_length=3)),
                ('form_html', models.TextField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='generic_addons_selected',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
