# Generated by Django 5.2.7 on 2025-12-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_day_work_best_privatebooking_service_schedules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='privateaddon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='privateaddon',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='pricing_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AddonRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('answer_value', models.CharField(max_length=200)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='home.privateaddon')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceQuestionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('answer_value', models.CharField(max_length=200)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='home.privateservice')),
            ],
        ),
    ]
