# Generated by Django 5.2.7 on 2025-12-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_schedulerule_privateaddon_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebooking',
            name='schedule_mode',
            field=models.CharField(choices=[('same', 'Same schedule for all services'), ('per_service', 'Separate schedule for each service')], default='same', max_length=20),
        ),
    ]
