# Generated by Django 5.2.7 on 2025-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_privatebooking_schedule_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatebooking',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='appointment_time_window',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='day_work_best',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='frequency_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privatebooking',
            name='special_timing_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
