# Generated by Django 5.2.7 on 2025-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_privatebooking_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('weekday', 'Specific Weekday'), ('date', 'Specific Date')], max_length=50)),
                ('weekday', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('surcharge_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
