# Generated by Django 5.2.7 on 2026-04-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_businessmaincategory_and_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablezipcode',
            options={'ordering': ['code'], 'verbose_name': 'Available Zip Code', 'verbose_name_plural': 'Available Zip Codes'},
        ),
        migrations.AlterModelOptions(
            name='notavailableziprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Unavailable Zip Request', 'verbose_name_plural': 'Unavailable Zip Requests'},
        ),
    ]
